name: Build on fedora
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        image: ["fedora:42"]
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build
        run: |
            docker run --rm \
            -v ${{ github.workspace }}:/root/src \
            -w /root/src \
            ${{ matrix.image }} \
            /bin/bash .travis-build.sh ${{ matrix.image }}
            
      - name: Check tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ ^refs/tags/v[0-9][0-9.]*$ ]] 
          then
            echo "match=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.check-tag.outputs.match == 'true'
        with:
          files: '*AppImage*'
         
